# -*- coding: utf-8 -*-
"""Desain Kasir Warung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sqljYjtuS7nrobN_JHDyQbmoX-9-Do4

# Desain Algoritma & Pseudocode

- Algoritma Tambah Item ke Keranjang
"""

def tambah_item_ke_keranjang(kode, qty, menu, keranjang):
  if kode not in menu:               # O(1) dict lookup
    return "error: Kode produk tidak ditemukan"

  produk = menu[kode]
  if produk['stok'] < qty:           # validasi stok
    return f"error: Stok tidak mencukupi: {produk['stok']}"

  # Linear search: apakah kode sudah ada di keranjang?
  found = False
  for item in keranjang:             # O(n) search
    if item['kode'] == kode:
      item['qty']      = item['qty'] + qty
      item['subtotal'] = item['qty'] * produk['harga']
      found = True
      break

  if not found:                      # item baru -> append
    keranjang.append({
      'kode'    : kode,
      'nama'    : produk['nama'],
      'harga'   : produk['harga'],
      'qty'     : qty,
      'subtotal': produk['harga'] * qty
    })

  return "sukses"

"""- Algoritma Hitung Total & Proses Pembayaran"""

# Pseudocode: hitung_total() + proses_pembayaran()
def hitung_total(keranjang):
  total = 0
  for item in keranjang:             # O(n) akumulasi
    total = total + item['subtotal']
  return total

def proses_pembayaran(total, uang_masuk):
  if uang_masuk < total:             # validasi
    return (False, 0, 'Uang kurang')
  kembalian = uang_masuk - total
  return (True, kembalian, 'OK')

"""- Algoritma Cetak Struk Digital"""

# Pseudocode: cetak_struk(keranjang, total, kembalian, id_trx)
from datetime import datetime

def format_rupiah(amount):
    return f"Rp {amount:,.0f}".replace(',', '.')

def cetak_struk(keranjang, total, kembalian, id_trx):
  LEBAR = 40  # karakter
  print('=' * LEBAR)
  print('KASIR WARUNG'.center(LEBAR))
  print(f'No: {id_trx}  {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}'.center(LEBAR))
  print('-' * LEBAR)

  for item in keranjang:             # O(n) iterasi
    nama_col  = item['nama'].ljust(20)
    qty_col   = str(item['qty']).center(4)
    harga_col = format_rupiah(item['subtotal']).rjust(12)
    print(nama_col + qty_col + harga_col)

  print('-' * LEBAR)
  print('TOTAL'.ljust(24) + format_rupiah(total).rjust(16))
  print('BAYAR'.ljust(24) + format_rupiah(kembalian+total).rjust(16))
  print('KEMBALI'.ljust(24) + format_rupiah(kembalian).rjust(16))
  print('=' * LEBAR)
  print('Terima kasih!'.center(LEBAR))

"""- Algoritma Validasi Input"""

# Pseudocode: validasi_input_angka(prompt, min_val, max_val)
def validasi_input_angka(prompt, min_val=0, max_val=None):
  while True:                        # loop sampai input valid
    try:
      nilai = int(input(prompt))     # bisa raise ValueError
      if nilai < min_val:
        print(f'Nilai minimal: {min_val}')
        continue
      if max_val is not None and nilai > max_val:
        print(f'Nilai maksimal: {max_val}')
        continue
      return nilai                   # input valid → return
    except ValueError:
      print('Input harus berupa angka!')
                                     # loop kembali ke WHILE

"""# Desain User Interface (Console-Based)

Layar Menu Utama
"""

def menu_utama():
    print("""
========================================
       KASIR WARUNG - v1.0
========================================
 Selamat datang, Operator!
----------------------------------------
 [1] Proses Transaksi (Kasir)
 [2] Manajemen Stok Produk
 [3] Laporan Transaksi Hari Ini
 [4] Keluar Program
----------------------------------------
    """)
    # Contoh pemanggilan fungsi input yang sudah dibuat sebelumnya:
    # pilihan = validasi_input_angka("Pilihan Anda [1-4]: ", 1, 4)

# Panggil fungsi untuk melihat hasilnya
menu_utama()

"""- Layar Kasir — Transaksi Aktif"""

def menu_kasir():
    print("""
========================================
     TRANSAKSI BARU - #TRX-003
========================================
 DAFTAR PRODUK TERSEDIA:
  Kode  Nama                Harga  Stok
  P001  Indomie Goreng    Rp3.500    48
  P002  Aqua 600ml        Rp4.000    29
  P003  Chitato 68g       Rp8.500    15
----------------------------------------
 KERANJANG BELANJA:
  Indomie Goreng   x2      Rp  7.000
  Aqua 600ml       x1      Rp  4.000
  -------------------------------------
  TOTAL                    Rp 11.000
----------------------------------------
 [1] Tambah Item    [3] Hapus Item
    """)

# Memanggil fungsi untuk menampilkan UI
menu_kasir()

"""- Layar Struk Digital"""

def contoh_output_struk():
    print("""
========================================
           KASIR WARUNG
    Jl. Contoh No.1, Jakarta Selatan
========================================
 No      : TRX-003
 Tanggal : 27-06-2026  10:45:23
----------------------------------------
 Item               Qty        Subtotal
----------------------------------------
 Indomie Goreng       2         Rp 7.000
 Aqua 600ml           1         Rp 4.000
----------------------------------------
 TOTAL                          Rp11.000
 BAYAR                          Rp20.000
 KEMBALI                         Rp9.000
========================================
     Terima kasih sudah berbelanja!
    Barang yang dibeli tidak dapat
           dikembalikan.
========================================
    """)

# Memanggil fungsi untuk menampilkan contoh output
contoh_output_struk()

"""- Layar Manajemen Stok"""

def menu_stok():
    print("""
========================================
      MANAJEMEN STOK PRODUK
========================================
 PRODUK SAAT INI:
  Kode  Nama                Harga  Stok
  P001  Indomie Goreng    Rp3.500    48
  P002  Aqua 600ml        Rp4.000    29
  P003  Chitato 68g       Rp8.500    15
----------------------------------------
 [1] Tambah Produk Baru
 [2] Update Harga Produk
 [3] Update Jumlah Stok
 [4] Kembali ke Menu Utama
    """)

# Memanggil fungsi untuk menampilkan UI
menu_stok()

"""- Layar Laporan Transaksi"""

def menu_laporan():
    print("""
========================================
    LAPORAN TRANSAKSI - SESI INI
========================================
  No.  ID       Waktu      Total
----------------------------------------
   1   TRX-001  10:30:12   Rp  8.500
   2   TRX-002  10:38:47   Rp 15.000
   3   TRX-003  10:45:23   Rp 11.000
----------------------------------------
  Jumlah Transaksi : 3
  Total Pendapatan : Rp 34.500
========================================
 [ENTER] Kembali ke Menu Utama
    """)

# Memanggil fungsi untuk menampilkan UI
menu_laporan()

"""# Alur Program Utama (Flowchart Tekstual)"""

# Alur Program — Top Level
# START
#   │
#   ├─── Inisialisasi menu_produk (dict default)
#   ├─── Inisialisasi riwayat_transaksi = []
#   ├─── counter_id = 1
#   │
#   └─▶ LOOP menu_utama()
#          │
#          ├── [1] Kasir ──▶ menu_kasir()
#          │      │
#          │      ├── tambah_item_ke_keranjang()
#          │      ├── hitung_total()
#          │      ├── proses_pembayaran()
#          │      ├── update_stok()
#          │      ├── cetak_struk()
#          │      └── simpan_riwayat()
#          │
#          ├── [2] Stok ───▶ menu_stok()
#          │      ├── tambah produk baru ke menu
#          │      └── update harga / stok
#          │
#          ├── [3] Laporan ▶ menu_laporan()
#          │      └── tampilkan_riwayat()
#          │
#          └── [4] Keluar
#                 │
#                END